### ISSUE TITLE
error

### ISSUE THREAD

**Issue by vikasrawal** [Ikke/ledger-dashboard#3]
I get the following errors when I run './runtests.sh'

```
File "utils/color_test_results", line 20
    print(t_out, end="")
                    ^

```

And this when I do 'python runserver.py'

```
Traceback (most recent call last):
  File "runserver.py", line 2, in <module>
    from ledgerdashboard import app
  File "/Users/vikas/ledger-dashboard/ledgerdashboard/__init__.py", line 5, in <module>
    from ledgerdashboard import views
  File "/Users/vikas/ledger-dashboard/ledgerdashboard/views.py", line 196
SyntaxError: Non-ASCII character '\xe2' in file /Users/vikas/ledger-dashboard/ledgerdashboard/views.py on line 196, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
``
```

**Comment by Ikke** [comment]
I think it's because of your locale. I need to add encoding directions to it, and need to make the currency symbol a setting anyway.

**Comment by Ikke** [comment]
@vikasrawal What error did you get in the first example? I'm not able to reproduce it. Are you running it as python2? Because I've mainly written it in python3

**Comment by blessedbiped** [comment]
Found it! I got the same error, but realized that pip is different than pip3 on Ubuntu systems. Regular pip only installed the requirements under 2.7, so the correct sequence to get this running on Ubuntu 14.04 is `sudo pip3 install -r requirements.txt`

I found another error while I was trying to run this, which was solved by removing the debug setting from runserver.py.
