### ISSUE TITLE
How to change euro symbol to others

### ISSUE THREAD

**Issue by blessedbiped** [Ikke/ledger-dashboard#5]
Got it working, but is there any way to get the currency symbols to show up correctly? My ledger journal is all in $, I thought it would pick that up but the page is showing €.

**Comment by Ikke** [comment]
I have a branch where I add support for other currencies. Please give it a try:

https://github.com/Ikke/ledger-dashboard/tree/feature/multiple-currencies

**Comment by blessedbiped** [comment]
Can't get the server up, it has an internal error(500). Had to change the locale setting in views.py line 16 to get that far as s.locale didn't work. Changed to 'en_US.utf8', and then it would start, but no error codes to the console. I'll try setting debug next to get more info

**Comment by blessedbiped** [comment]
Hmm, that certainly did something:

``` python
127.0.0.1 - - [26/Feb/2016 21:15:58] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.4/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.4/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/fuzzy/src/ledger-dashboard/ledgerdashboard/views.py", line 41, in index
    for account, cur, balance in l.balance(accounts=s.Accounts.ASSETS_PATTERN)
  File "/home/fuzzy/src/ledger-dashboard/ledgerdashboard/ledger/ledger.py", line 35, in balance
    if settings.LIMIT_CURRENCY:
AttributeError: 'module' object has no attribute 'LIMIT_CURRENCY'
```

**Comment by Ikke** [comment]
Did you update your local settings file from the template? I added some new config options.

**Comment by blessedbiped** [comment]
Yup, that was the problem. The dollar sign ($) is U+0024, seems to work here in place of USD

**Comment by Ikke** [comment]
Ok, closing issue.
